refactor sexy binary for new directory/plugin layout
Signed-off-by: Steven Armstrong <steven.armstrong@inf.ethz.ch>

diff --git a/bin/sexy b/bin/sexy
--- a/bin/sexy
+++ b/bin/sexy
@@ -21,23 +21,29 @@
 #  runs: ./plugins/network/extend/sexy/whatever
 #
 
+################################################################################
+# standard vars stolen from cconf, renamed for sexy
+__sexy_pwd="$(pwd -P)"
+__sexy_mydir="${0%/*}"; __sexy_abs_mydir="$(cd "$__sexy_mydir" && pwd -P)"
+__sexy_myname=${0##*/}; __sexy_abs_myname="$__sexy_abs_mydir/$__sexy_myname"
+__sexy_base_dir=$(cd "${bin_dir}/../"; pwd)
+export PATH="$__sexy_abs_mydir:$PATH"
+
+
 #set -x
 
-DEBUG=
-debug() {
-   if [ $DEBUG ]; then
-      echo "[DEBUG] $@" >&2
-   fi
+__sexy_exit_err() {
+   echo "[ERROR] $@" >&2
+   exit 1
 }
 
+__sexy_exit_usage() {
+   echo "Usage: $__sexy_myname <plugin> <action> [arg1, argn]" > &2
+   exit 1
+}
 
-command_name="${0##*/}"
-bin_dir=$(readlink -n -f "${0%/*}")
-export PATH="$bin_dir:$PATH"
-base_dir=$(cd "${bin_dir}/../"; pwd)
-
-: ${SEXY_DB_DIR:="${base_dir}/db"}
-debug "SEXY_DB_DIR: $SEXY_DB_DIR"
+: ${SEXY_DB_DIR:="${HOME}/.sexy/db"}
+mkdir -p "$SEXY_DB_DIR"
 
 if [ -n "$SEXY_PLUGIN_PATH" ]; then
    SEXY_PLUGIN_PATH="$SEXY_PLUGIN_PATH:${base_dir}/plugins"
@@ -48,34 +54,30 @@ fi
 
 find_plugin_dir() {
    local plugin_name="$1"
-   for path in $(echo "$SEXY_PLUGIN_PATH" | sed 's/:/\n/g'); do
+   for path in $(echo "$SEXY_PLUGIN_PATH" | sed 's/[^\]:/\n/g'); do
       [ -d "$path/$plugin_name" ] && echo "$path/$plugin_name"
    done
 }
 
-
+[ $# -ge 2  ] || __sexy_exit_usage "Missing arguments"
 
 plugin="$1"; shift
 action="$1"; shift
 
 case $action in
-   add|del|get|set|help)
-      command="$base_dir/libexec/$action"
+   help)
+      command="$__sexy_base_dir/libexec/$action"
       ;;
    *)
-      plugin_dir=$(find_plugin_dir $plugin)
-      debug "plugin_dir: $plugin_dir"
-      command="$plugin_dir/extend/$command_name/$action"
+      plugin_dir=$(find_plugin_dir "$plugin")
+      command="$plugin_dir/libexec/$action"
       ;;
 esac
 
-mkdir -p "$SEXY_DB_DIR"
-
-plugin_db_dir="$SEXY_DB_DIR/$plugin"
-debug "plugin_db_dir: $plugin_db_dir"
-mkdir -p "$plugin_db_dir"
-cd "$plugin_db_dir"
+# TODO: move to db plugin
+#plugin_db_dir="$SEXY_DB_DIR/$plugin"
+#mkdir -p "$plugin_db_dir"
+#cd "$plugin_db_dir"
 
 $command "$@"
-
 
